### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by fernandorpm**
# Milestone 1
> On this milestone we had to create the following components for our website:
> - navbar
> - highlights section
> - latest findings section
> - footer

## Files to add
- index.html
- styles.css
- .github/workflows/linters.yml
#### images/
- header1.jpg
- header2.webp
- header3.webp
- micro_logo.png

## Files to update
- README.md

## Extra info
All of the components built were made to work with both desktops, tablets, and smaller mobile devices.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# Changes Required :red_circle: 

**Hello team** you have done great job so far with this millstone

## To highlight:
- Good job with this millestone :muscle: 
- Your project looks almost the same as the original :+1: 

## Required Changes:
- [x] TNW logo should be present in the tablet version(medium version) tse1 tse2
- [x] The title of each article is a header (`hx` tag) and has a link (`a` tag)

## Latest funding section:
- [x] Please make the following as the original, see the pictures: 
testt
testt2
- [x] The title of the section has a link (`a` tag)
- [x] Each article has:
- is a link (`a` tag) 
- Two categories items, with a link (`a` tag)

## Footer:
- [x] It contains social media icons centered in a `nav` tag, please add them inside a nav

### **Please make the required changes and submit another review request when you are ready.**

<hr>
### if you have any question kindly reach me on slack @GzimAsani

### HAPPY CODING :computer:

**Comment by fernandorpm** [comment]
# Important to mention for the next reviewer
Please read this before reviewing our code.

The last reviewer asked us to adjust the navbar according to the website instead of the pathwright. So please, take into consideration that it was adjusted to meet his criteria. If you check a few commits before this one, you will be able to find the original navbar.

Thank you! :+1:

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1: 
Hello, team!
**Great job! I can see that you have implemented all the required changes. 
This PR has been approved. You can go ahead and merge the branch. Congratulations and good luck.** 

#
Any further questions? Please reach out to me on [slack](https://microverse-students.slack.com/team/U017N7LLZ40)

**Comment by fernandorpm** [comment]
# Milestone 1 finished
Project approved by @smcommits

**Pull request merged**
